[clustering]
mode = manager
replication_factor = 2
search_factor = 2
pass4SymmKey = changeme
cluster_label = playaroundit
multisite = false
summary_replication = true


[indexer_discovery]
pass4SymmKey = changeme
indexerWeightByDiskCapacity = true