[indexAndForward]
index = false

[indexer_discovery:clustered_indexers]
pass4SymmKey = <indexer_cluster_secret>
manager_uri = https://192.168.248.204:8089

[tcpout:primary_indexers]
indexerDiscovery = clustered_indexers
compressed = true

[tcpout]
defaultGroup = primary_indexers
forwardedindex.filter.disable = true  
indexAndForward = false 
forceTimebasedAutoLB = true
maxQueueSize = 7MB
useACK = true
