[volume:hot_tier]
path = /opt/splunkdata/hot
maxVolumeDataSizeMB = 500

[volume:cold_tier]
path = /opt/splunkdata/cold
maxVolumeDataSizeMB = 1000

[default]
repFactor = auto
tsidxWritingLevel = 4
homePath          = volume:hot_tier/$_index_name/db
coldPath          = volume:cold_tier/$_index_name/colddb
thawedPath        = /opt/splunkdata/thawed/$_index_name/thaweddb
tstatsHomePath    = volume:hot_tier/$_index_name/datamodel_summarys
summaryHomePath   = volume:hot_tier/$_index_name/report_summary
maxHotSpanSecs    = 14400
maxWarmDBCount    = 6
frozenTimePeriodInSecs = 604800
maxTotalDataSizeMB = 2048

[linux_audit]
frozenTimePeriodInSecs = 604800
maxTotalDataSizeMB = 512

[linux_logs]
frozenTimePeriodInSecs = 604800
maxTotalDataSizeMB = 512

[nginx_access]
frozenTimePeriodInSecs = 604800
maxTotalDataSizeMB = 256

[_internal]
frozenTimePeriodInSecs = 259200

[_introspection]
frozenTimePeriodInSecs = 259200