[volume:hot_tier]
path = /opt/splunkdata/hot
maxVolumeDataSizeMB = 2000

[volume:cold_tier]
path = /opt/splunkdata/cold
maxVolumeDataSizeMB = 5000

[default]
repFactor = auto
tsidxWritingLevel = 4
homePath   = volume:hot_tier/$_index_name/db
coldPath   = volume:cold_tier/$_index_name/colddb
thawedPath = /opt/splunkdata/thawed/$_index_name/thaweddb