[clustering]
manager_uri = https://192.168.248.204:8089
mode = peer
pass4SymmKey = changeme
multisite = false

[replication_port://9100]
disabled = false

[license]
manager_uri  = https://192.168.248.204:8089
